### PR TITLE
Improve command parsing, add prefix_only param

### PR DESCRIPTION
**Pull request by adamhigerd**
Currently, morgenbot will respond to !commands anywhere in the string. However, if the command isn't the first thing in the line it doesn't parse the arguments correctly, and if the command is unrecognized, it chops out the wrong thing when assembling the giphy parameter.

This PR fixes the arguments parsing and the giphy string and adds a configuration flag to only recognize !commands at the beginning of the input string, for users that desire that stricter behavior.

### CODE REVIEW

**Comment by eelzon** [comment]
Hey @adamhigerd -- I agree that command parsing should be prefix-only. If you update this PR to make that a requirement instead of a setting, I'll merge.

**Comment by adamhigerd** [comment]
@eelzon Oh geez. That's almost a year old. Um... Yeah, I can do that, but it's going to take me a while to get my head back into the code.

**Comment by eelzon** [comment]
@adamhigerd Take your time! I certainly took mine, ha. And yeah, the whole thing could use a refactor.

**Comment by adamhigerd** [comment]
@eelzon Done.

**Comment by eelzon** [comment]
@adamhigerd Looks great! Thanks for the whtiespace-killing too. Merging!

**Comment by adamhigerd** [comment]
Oh, my editor did that on its own when I hit save. XD

**Pull request merged**
